[package]
name = "pve-rs"
version = "0.8.9"
description = "PVE parts which have been ported to Rust"
homepage = "https://www.proxmox.com"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2021"
license = "AGPL-3"
repository = "https://git.proxmox.com/?p=proxmox.git"
exclude = [
    "debian",
]
[lib]
crate-type = [ "cdylib" ]
[dependencies]
anyhow = "1.0"
base32 = "0.4"
base64 = "0.13"
env_logger = "0.10"
hex = "0.4"
http = "0.2.7"
libc = "0.2"
log = "0.4.17"
nix = "0.26"
openssl = "0.10.40"
serde = "1.0"
serde_bytes = "0.11"
serde_json = "1.0"
url = "2"
perlmod = { version = "0.13", features = [ "exporter" ] , git = "https://git.proxmox.com/git/perlmod.git" }
proxmox-http = { version = "0.9", features = ["client-sync", "client-trait"] , git = "https://git.proxmox.com/git/proxmox.git" }
proxmox-notify = { version = "0.4", features = ["pve-context"] , git = "https://git.proxmox.com/git/proxmox.git" }
proxmox-tfa = { version = "4.0.4", features = ["api"] , git = "https://git.proxmox.com/git/proxmox.git" }

[dependencies.proxmox-time ]
git = "https://git.proxmox.com/git/proxmox.git"

[dependencies.proxmox-sys ]
git = "https://git.proxmox.com/git/proxmox.git"

[dependencies.proxmox-subscription ]
git = "https://git.proxmox.com/git/proxmox.git"

[dependencies.proxmox-resource-scheduling ]
git = "https://git.proxmox.com/git/proxmox-resource-scheduling.git"

[dependencies.proxmox-openid ]
git = "https://git.proxmox.com/git/proxmox.git"

[dependencies.proxmox-http-error ]
git = "https://git.proxmox.com/git/proxmox.git"

[dependencies.proxmox-apt ]
git = "https://git.proxmox.com/git/proxmox.git"
